//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WPF_DBFirst_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string ProdCategory { get; set; }
        public int price { get; set; }
        public int qty { get; set; }
    }
}
